name: Android CI/CD
on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17.x"
          cache: "gradle"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          cache: true

      - run: flutter pub get

      - run: flutter build apk --debug

      - uses: actions/upload-artifact@master
        with:
          name: app-debug.apk
          path: build/app/outputs/apk/debug/app-debug.apk
